---
title: "Conditionals & For Loops"
author: "Erica Dale"
date: "2022-08-10"
output: html_document
library(tidyverse)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Conditional statements

## Task 1
```{r}
pm2_5 <- 48 # particulate matter 2.5, an indicator for air quality

if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 >= 100 & pm2_5 < 150) {
  print("Unhealthy for sensitive groups")
} else {
  print("Health risk present")
}
```

## Task 2
```{r}
species <- c("blue whale")

if (str_detect(species, pattern = "whale")) {
  print("You found a whale!")
}
```

## Task 3
```{r}
max_airtemp_c <- 29

if (max_airtemp_c > 27) {
  print("Temperature too high")
} else
  print("Temperature OK")
```

## Task 4
```{r}
base_burrito <- 6.50
main_ingredient <- c("chicken")


if (main_ingredient == "veggie") {
  print(base_burrito)
} else if (main_ingredient == "chicken") {
  print(base_burrito + 3)
} else if (main_ingredient == "steak") {
  print(base_burrito + 3.25)
}

```



# For loops

## Task 5
```{r}
fish <- c(8, 10, 12, 23)
species <- c("goldfish", "tetras", "guppies", "mollies")
fish_proportions <- vector(mode = "numeric", length = length(fish))

for(i in seq_along(fish)) {
  prop <- (i / sum(fish))
  fish_proportions[i] <- prop
}

fish_proportions
```

## Task 6
```{r}
month.name

for(i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))
}
#Paste will glue together strings

month.name[5]
```

